シェルスクリプトなんもわからん

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -1,1 +1,38 @@
 #!/bin/bash
+
+set -u
+
+DOTPATH="$HOME/.dotfiles"
+BACKUPPATH="$HOME/.dotfiles-backup"
+COLOR_GRAY="\033[1;38;5;243m"
+COLOR_BLUE="\033[1;34m"
+COLOR_GREEN="\033[1;32m"
+COLOR_RED="\033[1;31m"
+COLOR_PURPLE="\033[1;35m"
+COLOR_YELLOW="\033[1;33m"
+COLOR_NONE="\033[0m"
+
+greeting() {
+  echo -e "\nHello, ${COLOR_BLUE}dotfiles${COLOR_NONE}.\n"
+}
+
+has() {
+  type "$1" > /dev/null 2>&1
+}
+
+error() {
+  echo -e "${COLOR_RED}Error: ${COLOR_NONE}$1"
+  exit 1
+}
+
+case "$1" in
+  version)
+    greeting
+    echo -e "`basename $0` version 1.0.0\n"
+    ;;
+  *)
+    echo -e "\n"
+    echo -e "Usage: `basename $0` <command>\n\n"
+    echo -e "   version\tShow version"
+    ;;
+esac
